tasks:
  - name: Start Halo
    init: |
      docker compose pull
    command: |
      docker compose up

ports:
  - name: Halo
    description: Halo Service Port
    port: 8090
    visibility: public
